### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by saman** [callmearta/clubhouse-desktop#1]
I couldn't login after hitting the "next" button; I'm not getting any feedback nor an SMS from the clubhouse.

Would you please upload the source code so everybody can debug it?

**Comment by callmearta** [comment]
Hi, Sorry to hear that.
Right now i'm not willing to publish the source because it's a mess :)) developing in 24 hours without any documentation on the apis is the reason.
I'll open source it in near future but right now could you please tell me what exactly happens?
You have to input your number like the following form: +(Country Code)(Phone Number) => +989022123321

**Comment by saman** [comment]
Hi, Thanks for the response.
You may push the code and anybody could help to improve it.

As I'm using this format, It's kinda a normal German number:
+4912345678911

**Comment by callmearta** [comment]
Yea i found the bug. Could you please tell me the maximum characters number a phone number can be? So i can fix the validation.

**Comment by callmearta** [comment]
Ok i've fixed the validation. now the phone number could be between 4 to 16 digits. Releasing a new version tonight. Thank you for pointing that out @saman

**Comment by saman** [comment]
Thanks, I don't know how you've fixed it; I recommend using a standard library like [liphonenumber](https://www.npmjs.com/package/libphonenumber-js).

**Comment by callmearta** [comment]
I think it's fixed within the new release. check it out. closing this issue for now
