### ISSUE TITLE
Windows XP issue

### ISSUE THREAD

**Issue by nexusvue** [callmearta/clubhouse-desktop#10]
Hey man, amazing work loving the recent build, having a few issues thought I'd drop em to help.

- On windows app launches in full screen, you have to go to view > toggle full screen and it resumes to window, should be the other way around?
- Unable to open developer tools, settings or any other pop-up/contextual menu or sub-options
- Unable to get any voice through, this is probably due to not being able to get into settings?

**Comment by callmearta** [comment]
Hi, Thanks. I don't have a Windows pc to test and fix things you mentioned.
But the developer tools is disabled in the prebuilt versions. You can enable it by cloning the source code and changing the devTools:false to devTools:true and then running it on your own.
For the voice issue i think it may be because of the XP since it's a really really old version of Windows.

**Comment by nexusvue** [comment]
Hey Buddy - Fixed all voice issues etc, and have actively patched out some of the bugs, will do a commit with those changes next week.
